<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFQbP7zE\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFQbP7zE/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFQbP7zE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFQbP7zE\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerFQbP7zE\srcApp_KernelProdContainer([
    'container.build_hash' => 'FQbP7zE',
    'container.build_id' => 'e5d63826',
    'container.build_time' => 1616773808,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFQbP7zE');
