<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL2pXchY\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL2pXchY/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerL2pXchY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerL2pXchY\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerL2pXchY\srcApp_KernelProdContainer([
    'container.build_hash' => 'L2pXchY',
    'container.build_id' => 'd0006411',
    'container.build_time' => 1616771076,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL2pXchY');
