<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6kk1HfI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6kk1HfI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6kk1HfI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6kk1HfI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6kk1HfI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6kk1HfI',
    'container.build_id' => '4236e8fe',
    'container.build_time' => 1616770336,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6kk1HfI');
