<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7kDQNud\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7kDQNud/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7kDQNud.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7kDQNud\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7kDQNud\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7kDQNud',
    'container.build_id' => '3900e82a',
    'container.build_time' => 1617624609,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7kDQNud');
