<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWoGgDzw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWoGgDzw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWoGgDzw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWoGgDzw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWoGgDzw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WoGgDzw',
    'container.build_id' => '7cdf9f52',
    'container.build_time' => 1617810085,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWoGgDzw');
